services:
  atlas:
    build: .
    ports:
      - "127.0.0.1:6767:6767"
    environment:
      TZ: Europe/Stockholm
      ATLAS_DB_URL: postgresql://atlas:atlas@db:5432/atlas
      ATLAS_HIVE_API_URL: http://nyckeln:7004/api/v1
      ATLAS_HIVE_API_KEY: secret
      ATLAS_OIDC_ISSUER_URL: http://nyckeln:7003
      ATLAS_OIDC_CLIENT_ID: client-id
      ATLAS_OIDC_CLIENT_SECRET: client-secret
      ATLAS_DARKMODE_URL: no
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: ./templates
          action: rebuild
        - path: ./locales
          action: rebuild
        - path: ./migrations
          action: rebuild
        - path: ./Cargo.*
          action: rebuild
        - path: ./static
          action: sync
          target: /atlas/static
        - path: ./atlas.toml
          action: sync+restart
          target: /atlas/atlas.toml
        - path: ./splash.txt
          action: sync+restart
          target: /atlas/splash.txt
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - atlas-db-data:/data/db
    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: atlas
      PG_DATA: /data/db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "atlas"]
      interval: 2s
      timeout: 2s
      retries: 3
  nyckeln:
    build: ../nyckeln-under-dorrmattan
    #image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    configs:
      - source: nyckeln.yaml
        target: /config.yaml
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004

configs:
  nyckeln.yaml:
    content: |
      clients:
        - id: "client-id" # use this in your oidc client
          secret: "client-secret" # use this in your oidc client
          allows_guests: false
          redirect_uris: # URIs of your oidc client
            - http://localhost:6767/auth/oidc-callback

      users:
        - ug_kth_id: some-id
          kth_id: turetek
          email: turetek@kth.se
          first_name: Ture
          family_name: Teknolog
          picture: https://thskth.se/wp-content/uploads/2023/06/ths-logo-bla-01-300x294-1.png
          thumbnail: https://thskth.se/wp-content/uploads/2019/12/ths-logo-svart-01.png
        - ug_kth_id: some-id-2
          kth_id: marmas
          email: marmas@kth.se
          first_name: Markus
          family_name: Maskinare
          picture: https://thskth.se/wp-content/uploads/2023/06/ths-logo-bla-01-300x294-1.png
          thumbnail: https://thskth.se/wp-content/uploads/2019/12/ths-logo-svart-01.png

      hive:
        tokens:
        groups:
          - name: Systemansvarig
            id: d-sys
            domain: example.com
            members:
              - turetek
            tags:
              - id: post-manager
            permissions:
              - id: manage-tags
                scope: null
              - id: use-tag
                scope: "*"
              - id: post
                scope: null
          - name: Testgrupp
            id: test
            domain: ddagen.se
            members:
              - turetek
              - marmas
            tags:
              - id: post-manager

volumes:
  atlas-db-data:
