[package]
name = "ace"
version = "0.1.0"
edition = "2024"
description = "ACE - Atlas Calander Expression. A simple boolean expression language for filtering events in Atlas."
authors = ["Emma Ericsson <emma@krlsg.se>", "Oskar Engström <osen@datasektionen.se>"]

[dependencies]
ace_derive = { path = "./ace_derive" }
derive_more = { version = "2.1.1", features = ["from"] }
